# Generated by Django 4.2.4 on 2023-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('title_2', models.CharField(max_length=255, verbose_name='辅助书名')),
                ('cover_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('book_url', models.CharField(max_length=255, verbose_name='书籍链接')),
                ('base_info', models.CharField(max_length=255, verbose_name='基本')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版商')),
                ('publish_date', models.CharField(max_length=255, verbose_name='日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('rating', models.FloatField(verbose_name='评分')),
                ('review_count', models.IntegerField(verbose_name='评论人数')),
                ('summary', models.TextField(verbose_name='简介')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_readability', models.BooleanField(verbose_name='可试读')),
            ],
        ),
    ]
