# Generated by Django 4.2.4 on 2023-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanbooks',
            name='douban_id',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='豆瓣ID'),
            preserve_default=False,
        ),
    ]
