# Generated by Django 4.2.4 on 2023-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_books', '0002_doubanbooks_douban_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanbooks',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='base_info',
            field=models.CharField(max_length=255, null=True, verbose_name='基本'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='book_url',
            field=models.CharField(max_length=255, null=True, verbose_name='书籍链接'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='cover_path',
            field=models.CharField(max_length=255, null=True, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='is_readability',
            field=models.BooleanField(null=True, verbose_name='可试读'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='publish_date',
            field=models.CharField(max_length=255, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='publisher',
            field=models.CharField(max_length=255, null=True, verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='rating',
            field=models.FloatField(null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='review_count',
            field=models.IntegerField(null=True, verbose_name='评论人数'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='summary',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='title_2',
            field=models.CharField(max_length=255, null=True, verbose_name='辅助书名'),
        ),
    ]
