# Generated by Django 4.2.4 on 2023-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_books', '0003_alter_doubanbooks_author_alter_doubanbooks_base_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanBookCrawlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('is_ok', models.BooleanField(default=False)),
            ],
        ),
    ]
