# Generated by Django 4.2.4 on 2023-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_books', '0005_alter_doubanbooks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanbooks',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='cover_path',
            field=models.ImageField(max_length=255, null=True, upload_to='images/douban_books/cover_path', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='douban_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='豆瓣书籍ID'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='publish_date',
            field=models.CharField(max_length=100, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='publisher',
            field=models.CharField(max_length=100, null=True, verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='doubanbooks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='书名'),
        ),
    ]
